### ISSUE TITLE
Error when using transformImage

### ISSUE THREAD

**Issue by zmiller22** [scijava/jgo#47]
I am having problems using the `transformImage` command, but can't quite figure out what the error message means. I am trying to apply a transform from a BigWarp landmarks.csv file using the following command, and getting the following error message. On thing I was thinking is perhaps I have missed a step in my set up, but I installed Maven and jgo and have tested both. I would go look in the code myself, but I am not really sure where jgo is linking to... 

```
./transformImage \
-i  \
/mnt/c/Users/TracingPC1/Desktop/BIGWARP/VOLUMES/isotropic_stitched_ch01_rotate90_flipZ_flipV.nii \
-o  \
/mnt/c/Users/TracingPC1/Desktop/BIGWARP/TRANSFORMS/190529_Transforms/isotropic_stitched_ch01_rotate90_flipZ_flipV_antsTest.nii \
-t \
/mnt/c/Users/TracingPC1/Desktop/BIGWARP/TRANSFORMS/190529_Transforms/landmarks.csv \
-j 4                                                                                
 
```

`Exception in thread "main" picocli.CommandLine$ExecutionException: Error while calling command (process.TransformImage@32a068d1): java.lang.NullPointerException                                                                                                                                                                  at picocli.CommandLine.execute(CommandLine.java:1068)                                                                                                        at picocli.CommandLine.access$900(CommandLine.java:142)                                                                                                      at picocli.CommandLine$RunLast.handle(CommandLine.java:1255)                                                                                                 at picocli.CommandLine$RunLast.handle(CommandLine.java:1223)                                                                                                 at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1131)                                                                   at picocli.CommandLine.parseWithHandlers(CommandLine.java:1414)                                                                                              at picocli.CommandLine.call(CommandLine.java:1690)                                                                                                           at picocli.CommandLine.call(CommandLine.java:1614)                                                                                                           at process.TransformImage.main(TransformImage.java:89)                                                                                               Caused by: java.lang.NullPointerException                                                                                                                            at net.imglib2.realtransform.AbstractRealTransformSequence.add(AbstractRealTransformSequence.java:73)                                                        at org.janelia.saalfeldlab.transform.io.TransformReader.readTransforms(TransformReader.java:46)                                                              at process.TransformImage.setup(TransformImage.java:114)                                                                                                     at process.TransformImage.call(TransformImage.java:134)                                                                                                      at process.TransformImage.call(TransformImage.java:46)                                                                                                       at picocli.CommandLine.execute(CommandLine.java:1061)                                                                                                        ... 8 more `

**Comment by zmiller22** [comment]
My apologies I posted this on the wrong githib thread
